spring:
  profiles:
    active: ${PROFILE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /api/swagger.html

vaadin:
  urlMapping: /ui/*
  whitelisted-packages: com/kovalenko/deployer
