spring:
  profiles:
    active: ${PROFILE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger.html

vaadin:
  urlMapping: /ui/*
  whitelisted-packages:
    - com/kovalenko/deployer/frontend/view

application:
  config:
    default:
      username: ${DEFAULT_USER_NAME}
      password: ${DEFAULT_USER_PASSWORD}
